### PR TITLE
Clone of New York Times article page

### PR DESCRIPTION
**Pull request by IbrohimRasulov**
# New York Times article page
<h3><a href="https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0">Original Page link</a></h3>

<h2>Requirements</h2>
<p>• Using sementic tags ✅ </p>
<p>• Using positioning elements ✅ </p>
<p>• Inserting Flexbox and Grid systems ✅ </p>

### CODE REVIEW

**Comment by IbrohimRasulov** [comment]
This is the unfinished clone of the New York Times article page. After taking reviews, I will submit the full version, I just need a bit more time:)

**Review by smcommits — COMMENTED** [review]
# Status: Invalid :stop_sign: 
## Hello, @IbrohimRasulov. The PR you have submitted contains a project that is not complete and is not working. You should submit a working project. If you cannot fix it by yourself, reach out to a full-time TSE. [This article](https://microverse.zendesk.com/hc/en-us/articles/360026625973-How-can-I-get-help-from-TSEs-) describes how to set up a meeting with full-time TSEs.This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @IbrohimRasulov    ! :wave: :wave:

#### You have done well so far,  I had to take a second look cause your project looks almost exactly like the actual site!  :clap: :clap: However, there are changes required for you to make in order for this project to be approved. Kindly work on them and submit them for another code review. _**Note that you now have only 2 reviews left before you reach your review limit, so make all of the requested changes before submitting for review.**_ 😸 
- - -

### **Recommended**

**General**
- [x] You have to write a descriptive Pull Request Message with a descriptive title as well. It's essential that your repository is professional, as this is one of the things that potential colleagues will look at when recruiting team members. Please refer to [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/) for more information.
- [x] Remove every unnecessary file from the project, like the DS_store in your root folder.
- [x] Your readme should include :
- How to clone the project,
- The syntax used to add links is [name](link address). Use this syntax for adding links like the live demo, the authors' contact, etc. See [here](https://www.markdownguide.org/cheat-sheet/) for more markdown syntaxes. 

**Section Specific requirements**
- [x] The Editors' Picks sidebar should be placed in an `aside` tag.
- [x] Please remove the advertisement rows you've added throughout the project. 
- [x] Some parts of the main content texts have fonts that are larger than what is on the page. I'll recommend using [this](https://chrome.google.com/webstore/detail/font-picker/mmjbimgpcbaegjiieojddickpjbdkeej) chrome extension tool to help with this.


__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by IbrohimRasulov** [comment]
I changed the title of the pull request and message, also removed unnecessary files. README file has been updated. Missing parts of the project have been added.

**Review by smcommits — CHANGES_REQUESTED** [review]
# Stauts: Changes Required
## Hello, @IbrohimRasulov! You have done a great job. The website is extremely identical to the original. To make this project even better, you still have to address an issue that was pointed out by the previous TSE. 

## Required Changes

#### You still haven't addressed the following issue pointed out by the previous TSE
- [ ] **Please use aside tag for the editor's pick section**



This is a mandatory requirement for the project. 

Screenshot of the requirement in pathwright
:---------------------------------------------------------:
aside_requirement

Editor's Pick Section 
:--------------------------:
Screenshot_2021-03-27 Space Ripples Reveal Big Bang’s Smoking Gun



### Why is this Important? 

Aside tag is a Semantic Tag and is very beneficial for SEO.  The aside allows search engines to quickly pull information. This tag can be also used to enclose additional content that is related to a whole page, not just to a particular article. For example, aside can wrap a sidebar, ad, footnote, and so on.


# 

### Please request another review from your dashboard once you have implemented the changes. 

### :warning: As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 1 code review left for this project. If you think that the code review was not fair, you can request a second-opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

### Please reach out to me on [Slack](https://microverse-students.slack.com/team/U017N7LLZ40) if you need any assistance.

**Review by smcommits — APPROVED** [review]
# Status: Approved :+1: 
## Hello, @IbrohimRasulov! Great work implementing all the changes. Your website looks amazing. This PR is now approved. You can go ahead and merge the branch. Congratulations and good luck with your next project.

**Pull request merged**
